// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cdwtsrzshpotkfbyyyjk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNkd3RzcnpzaHBvdGtmYnl5eWprIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0NjQxNzMsImV4cCI6MjA2NDA0MDE3M30.n6qYEgtmWapgLOyuLva_o6-mBXnxkxIdbVFxxlSEcR4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);